# features/ai/ai_detection.py
import logging
import os
import json
import re

from aiogram import Router, F
from aiogram.filters import Command, StateFilter
from aiogram.types import Message, InlineKeyboardMarkup, InlineKeyboardButton
from aiogram.fsm.context import FSMContext
from features.ielts_checkup_ui import main_user_keyboard
from features.admin_feedback import send_admin_card, store_writing_essay

from database import get_user_mode, set_user_mode, clear_user_mode

import openai

logger = logging.getLogger(__name__)
router = Router()

AI_MODE = "ai_detect"
WAITING_FOR_TEXT = "ai_detect_text"

openai.api_key = os.getenv("OPENAI_API_KEY")

MIN_WORDS = 120
MAX_TELEGRAM_LEN = 4000

SYSTEM_PROMPT = """
You are an AI text analysis system.

Your task is to estimate the likelihood that a text was generated by an AI language model.

IMPORTANT INTERPRETATION RULES:
- AI likelihood is a PROBABILITY, not a factual claim.
- It does NOT mean how much of the text was written by AI.
- It reflects how closely the text's patterns resemble typical AI-generated language.

CRITICAL DISTINCTIONS (VERY IMPORTANT):
- Poor grammar, awkward phrasing, spelling mistakes, and inconsistent errors are STRONG indicators of HUMAN writing, especially by non-native speakers.
- AI-generated text usually has:
  • consistent grammar
  • smooth sentence flow
  • balanced vocabulary
  • minimal random errors
- Do NOT treat low language proficiency, learner-style English, or exam-template writing as AI signals by default.

WHEN LOWERING AI LIKELIHOOD:
- Frequent and inconsistent grammatical mistakes
- Literal translations from another language
- Uneven sentence quality
- Redundant or messy rewriting
- Emotional or culturally specific additions that feel spontaneous

WHEN RAISING AI LIKELIHOOD:
- Overly smooth, polished, and predictable language
- Uniform sentence length and structure
- Formulaic transitions used perfectly throughout
- High coherence with low variation
- Repetition that appears optimized, not accidental

OUTPUT REQUIREMENTS:
- Never accuse the user.
- Never say "written by AI".
- Never mention specific AI models.
- Be neutral and cautious.
- If signals are mixed, prefer MEDIUM or LOW confidence.

You must return STRICT JSON ONLY in the following format:

{
  "ai_probability": "<integer 0–100>",
  "confidence": "<Low | Medium | High>",
  "explanation": "<2–3 short neutral sentences explaining the probability>",
  "ai_segments": "<brief description of where AI-like patterns may appear, or 'No specific segments strongly stand out'>"
}

RULES:
- No markdown.
- No extra text.
- No explanations outside JSON.
- If the text appears clearly human-written but structured, keep AI probability BELOW 50.

CRITICAL CALIBRATION RULE (IELTS / NON-NATIVE WRITING):
- If the text contains frequent grammatical errors, broken sentence structures, awkward collocations, or unclear phrasing typical of non-native learners, the AI probability MUST NOT exceed 45%, even if the text has basic structure (introduction, body, conclusion).
- Organized structure alone is NOT a strong signal of AI. IELTS-style essay templates and simple logical organization are common in human student writing.
When human and AI signals are mixed, always prefer LOWER confidence and keep AI probability below 50.

"""

# ─────────────────────────────
# Helpers
# ─────────────────────────────

def _ai_color_tone(ai_probability: int) -> str:
    if ai_probability < 30:
        return "🟢"
    elif ai_probability < 50:
        return "🟤"
    elif ai_probability < 70:
        return "🟠"
    else:
        return "🔴"

def _safe_int(value, default=0):
    try:
        value = str(value).replace("%", "").strip()
        num = int(float(value))
        return max(0, min(100, num))
    except Exception:
        return default

def _word_count(text: str) -> int:
    return len(re.findall(r"\b\w+\b", text))

def _next_actions_keyboard():
    return InlineKeyboardMarkup(
        inline_keyboard=[
            [
                InlineKeyboardButton(text="✨ Humanize text", callback_data="ai_humanize"),
                InlineKeyboardButton(text="🔍 Check plagiarism", callback_data="ai_plagiarism"),
            ],
            [
                InlineKeyboardButton(text="🔁 Re-check AI score", callback_data="ai_recheck"),
                InlineKeyboardButton(text="⬅️ Back", callback_data="ai_back"),
            ],
        ]
    )

def _format_result(data: dict) -> str:
    raw_prob = data.get("ai_probability", 0)
    ai_prob = _safe_int(raw_prob)
    color = _ai_color_tone(ai_prob)

    return (
        f"<b>🤖 AI Detection Result</b>\n\n"
        f"<b>AI likelihood:</b> {ai_prob}% {color}\n"
        f"<b>Confidence:</b> {data.get('confidence','—')}\n\n"
        f"<b>🧠 Explanation</b>\n{data.get('explanation','—')}\n\n"
        f"<b>🔎 AI-like patterns</b>\n{data.get('ai_segments','—')}"
    )


def _ai_keyboard():
    from aiogram.types import ReplyKeyboardMarkup, KeyboardButton
    return ReplyKeyboardMarkup(
        keyboard=[[KeyboardButton(text="❌ Cancel")]],
        resize_keyboard=True
    )


# ─────────────────────────────
# Entry (UI / command triggers this)
# ─────────────────────────────

@router.message(Command("ai_detect"))
async def start_ai_detect(message: Message, state: FSMContext):
    uid = message.from_user.id

    # 🔒 Do NOT start if another mode is active
    if get_user_mode(uid) not in (None, AI_MODE):
        return

    set_user_mode(uid, AI_MODE)
    await state.set_state(WAITING_FOR_TEXT)
    await state.update_data(text=None)

    await message.answer(
        "🧠 <b>AI Detection</b>\n\n"
        "Tekshirmoqchi bo‘lgan matnni yuboring.\n"
        f"(Kamida {MIN_WORDS} so‘z)",
        parse_mode="HTML",
        reply_markup=_ai_keyboard()
    )


async def _ocr_image_to_text(bot, photos):
    try:
        photo = photos[-1]
        file = await bot.get_file(photo.file_id)
        image_bytes = await bot.download_file(file.file_path)

        import base64
        image_b64 = base64.b64encode(image_bytes.read()).decode("utf-8")
        image_data_url = f"data:image/jpeg;base64,{image_b64}"

        response = await openai.ChatCompletion.acreate(
            model="gpt-4o-mini",
            messages=[
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": "Extract ALL readable text. Return ONLY text."},
                        {"type": "image_url", "image_url": {"url": image_data_url}},
                    ],
                }
            ],
            max_tokens=800,
        )

        return response["choices"][0]["message"]["content"].strip()

    except Exception:
        logger.exception("OCR failed in AI Detection")
        return ""



# ─────────────────────────────
# Collect Text (NOT GLOBAL)
# ─────────────────────────────

@router.message(StateFilter(WAITING_FOR_TEXT), F.text != "❌ Cancel")
@router.message(StateFilter(WAITING_FOR_TEXT), F.photo)
async def collect_text(message: Message, state: FSMContext):
    uid = message.from_user.id
    if get_user_mode(uid) != AI_MODE:
        return

    if message.text:
        text = message.text.strip()
    elif message.photo:
        await message.answer("🖼️ Rasm ichidagi matn o‘qilmoqda...")
        text = await _ocr_image_to_text(message.bot, message.photo)
    else:
        await message.answer("❗️Matn yoki rasm yuboring.")
        return

    words = _word_count(text)

    if words < MIN_WORDS:
        await message.answer(
            f"⚠️ Matn juda qisqa.\n"
            f"Kamida {MIN_WORDS} so‘z bo‘lishi kerak.\n"
            f"Hozirgi: {words} so‘z."
        )
        return

    await state.update_data(text=text)
    await message.answer("⏳ <b>Matn tahlil qilinmoqda...</b>", parse_mode="HTML")

    await analyze_text(message, state)

# ─────────────────────────────
# Analyze
# ─────────────────────────────

async def analyze_text(message: Message, state: FSMContext):
    uid = message.from_user.id
    if get_user_mode(uid) != AI_MODE:
        return

    data = await state.get_data()
    text = data.get("text", "")

    try:
        response = await openai.ChatCompletion.acreate(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            max_tokens=400,
        )

        raw = response["choices"][0]["message"]["content"]
        ai_data = json.loads(raw)

        try:
            prob = _safe_int(ai_data.get("ai_probability", 0))
            if prob <= 30:
                await store_writing_essay(message.bot, text, "#ai_detect_clean")
        except Exception:
            logger.exception("Failed to store AI Detector text")


    except Exception:
        logger.exception("AI Detection failed")
        ai_data = {
            "ai_probability": "—",
            "confidence": "Low",
            "explanation": "Tahlil jarayonida texnik xatolik yuz berdi.",
            "ai_segments": "Aniqlanmadi."
        }

    output = _format_result(ai_data)

    await message.answer(
        output,
        parse_mode="HTML"
        #reply_markup=_next_actions_keyboard()
    )
    await send_admin_card(message.bot, uid, "New AI Detection", output)
    await state.clear()
    clear_user_mode(uid)

    await message.answer("✔️ Tekshiruv yakunlandi.", reply_markup=main_user_keyboard())

# ─────────────────────────────
# Cancel
# ─────────────────────────────

@router.message(F.text == "❌ Cancel", StateFilter(WAITING_FOR_TEXT))
async def cancel_anytime(message: Message, state: FSMContext):
    uid = message.from_user.id
    if get_user_mode(uid) != AI_MODE:
        return

    await state.clear()
    clear_user_mode(uid)
    await message.answer("❌ Bekor qilindi.", reply_markup=main_user_keyboard())
